###
### Retrieve a token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}

> {%
client.test(
    "Request executed successfully",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);

client.test(
    "Response body contains a token",
    function() {
        client.assert(response.body.token !== undefined, "Token not found in response body");
    }
);
%}
